import { UserInfo } from '@/lib/services/types';

export const mockedUsers: UserInfo[] = [
  {
    id: "1",
    name: "Ana",
    lastName: "Silva",
    email: "ana.silva@example.com",
    biografia: "Estudante apaixonada por medicina.",
    fotoPerfil: "/placeholder.svg?height=100&width=100",
    avatar: "/placeholder.svg?height=100&width=100",
    universidade: "USP",
    curso: "Medicina",
    semestre: 6,
    regiaoDeInteresse: "São Paulo",
    interesses: ["SAUDE_E_BEM_ESTAR", "NATUREZA", "CULINARIA"],
    roles: ["user"],
    createdAt: "2024-01-01T10:00:00Z",
    updatedAt: "2024-06-01T10:00:00Z",
  },
  {
    id: "2",
    name: "Pedro",
    lastName: "Oliveira",
    email: "pedro.oliveira@example.com",
    biografia: "Futuro engenheiro civil.",
    fotoPerfil: "/placeholder.svg?height=100&width=100",
    avatar: "/placeholder.svg?height=100&width=100",
    universidade: "UNICAMP",
    curso: "Engenharia Civil",
    semestre: 8,
    regiaoDeInteresse: "Campinas",
    interesses: ["NEGOCIOS", "ESPORTES", "TECNOLOGIA"],
    roles: ["user"],
    createdAt: "2023-11-15T14:20:00Z",
    updatedAt: "2024-05-30T09:00:00Z",
  },
  {
    id: "3",
    name: "Mariana",
    lastName: "Costa",
    email: "mariana.costa@example.com",
    biografia: "Criativa e detalhista, ama desenhar prédios.",
    fotoPerfil: "/placeholder.svg?height=100&width=100",
    avatar: "/placeholder.svg?height=100&width=100",
    universidade: "UFRJ",
    curso: "Arquitetura",
    semestre: 7,
    regiaoDeInteresse: "Rio de Janeiro",
    interesses: ["ARTE", "FOTOGRAFIA", "MODA"],
    roles: ["user"],
    createdAt: "2024-02-10T08:00:00Z",
    updatedAt: "2024-06-28T15:30:00Z",
  },
  {
    id: "4",
    name: "Lucas",
    lastName: "Santos",
    email: "lucas.santos@example.com",
    biografia: "Apaixonado por justiça e debates.",
    fotoPerfil: "/placeholder.svg?height=100&width=100",
    avatar: "/placeholder.svg?height=100&width=100",
    universidade: "UFMG",
    curso: "Direito",
    semestre: 9,
    regiaoDeInteresse: "Belo Horizonte",
    interesses: ["LITERATURA", "CINEMA", "EDUCACAO"],
    roles: ["user"],
    createdAt: "2023-05-12T13:00:00Z",
    updatedAt: "2024-06-25T18:00:00Z",
  },
  {
    id: "5",
    name: "Juliana",
    lastName: "Pereira",
    email: "juliana.pereira@example.com",
    biografia: "Interessada no comportamento humano.",
    fotoPerfil: "/placeholder.svg?height=100&width=100",
    avatar: "/placeholder.svg?height=100&width=100",
    universidade: "PUC",
    curso: "Psicologia",
    semestre: 5,
    regiaoDeInteresse: "Rio de Janeiro",
    interesses: ["SAUDE_E_BEM_ESTAR", "MUSICA", "VIAGENS"],
    roles: ["user"],
    createdAt: "2023-09-20T10:00:00Z",
    updatedAt: "2024-05-10T15:00:00Z",
  },
  {
    id: "6",
    name: "Rafael",
    lastName: "Mendes",
    email: "rafael.mendes@example.com",
    biografia: "Codando desde os 12 anos.",
    fotoPerfil: "/placeholder.svg?height=100&width=100",
    avatar: "/placeholder.svg?height=100&width=100",
    universidade: "UnB",
    curso: "Ciência da Computação",
    semestre: 4,
    regiaoDeInteresse: "Brasília",
    interesses: ["TECNOLOGIA", "JOGOS", "CINEMA"],
    roles: ["user"],
    createdAt: "2024-01-15T09:30:00Z",
    updatedAt: "2024-06-10T12:00:00Z",
  },
  {
    id: "7",
    name: "Camila",
    lastName: "Rocha",
    email: "camila.rocha@example.com",
    biografia: "Apaixonada por gestão e inovação.",
    fotoPerfil: "/placeholder.svg?height=100&width=100",
    avatar: "/placeholder.svg?height=100&width=100",
    universidade: "UFPE",
    curso: "Administração",
    semestre: 6,
    regiaoDeInteresse: "Recife",
    interesses: ["NEGOCIOS", "MODA", "VIAGENS"],
    roles: ["user"],
    createdAt: "2023-10-01T08:00:00Z",
    updatedAt: "2024-06-11T10:00:00Z",
  },
  {
    id: "8",
    name: "Bruno",
    lastName: "Ferreira",
    email: "bruno.ferreira@example.com",
    biografia: "Fã de carros, motores e mecânica.",
    fotoPerfil: "/placeholder.svg?height=100&width=100",
    avatar: "/placeholder.svg?height=100&width=100",
    universidade: "UFSC",
    curso: "Engenharia Mecânica",
    semestre: 7,
    regiaoDeInteresse: "Florianópolis",
    interesses: ["TECNOLOGIA", "ESPORTES", "NATUREZA"],
    roles: ["user"],
    createdAt: "2023-08-18T07:00:00Z",
    updatedAt: "2024-06-07T14:00:00Z",
  },
  {
    id: "9",
    name: "Larissa",
    lastName: "Martins",
    email: "larissa.martins@example.com",
    biografia: "Amante dos animais e da natureza.",
    fotoPerfil: "/placeholder.svg?height=100&width=100",
    avatar: "/placeholder.svg?height=100&width=100",
    universidade: "UNESP",
    curso: "Veterinária",
    semestre: 5,
    regiaoDeInteresse: "Botucatu",
    interesses: ["NATUREZA", "CULINARIA", "FOTOGRAFIA"],
    roles: ["user"],
    createdAt: "2023-07-22T16:00:00Z",
    updatedAt: "2024-06-05T08:30:00Z",
  },
  {
    id: "10",
    name: "Gabriel",
    lastName: "Lima",
    email: "gabriel.lima@example.com",
    biografia: "Curioso sobre como o mundo funciona.",
    fotoPerfil: "/placeholder.svg?height=100&width=100",
    avatar: "/placeholder.svg?height=100&width=100",
    universidade: "UFPR",
    curso: "Economia",
    semestre: 8,
    regiaoDeInteresse: "Curitiba",
    interesses: ["NEGOCIOS", "EDUCACAO", "LITERATURA"],
    roles: ["user"],
    createdAt: "2023-06-01T11:00:00Z",
    updatedAt: "2024-06-04T12:00:00Z",
  },
  // ... Continue para os usuários 11 a 20 se quiser ...
];