
export const FEATURES_MOCK = [
  "MOBILIADO",
  "AR_CONDICIONADO",
  "INTERNET",
  "ACEITA_PETS",
  "PISCINA",
  "CHURRASQUEIRA",
  "ACADEMIA",
  "GARAGEM",
  "VARANDA",
  "AREA_DE_SERVICO",
  "PORTARIA_24H",
  "SALAO_DE_FESTAS",
  "ELEVADOR",
  "GAS_ENCANADO",
  "ARMARIOS_EMBUTIDOS",
  "LAVANDERIA_NO_LOCAL",
  "BICICLETARIO",
  "TRANSPORTE_PUBLICO_PROXIMO"
]